package Coursework;

import Coursework.DataClasses.Tech;

import java.util.LinkedList;
import java.util.Scanner;

public class Add{

    Scanner input = new Scanner(System.in);
    String type,name,TSS,COD,BOD,area,energy; //all parameters of linked list except code, since code is automatically generated by system
    int code=1; //default code number

    public LinkedList<Tech> Insert(LinkedList<Tech> holdTech) {

        NumTest test = new NumTest(); //to test if string is int or double

        while(true){

            System.out.println("Enter type:");
            type = input.nextLine(); //get type

            if(test.isInt(type)){
                break; //break loop if type is int
            }
            else{
                System.out.println("Invalid input.");
            }
        }

        System.out.println("Enter name:");
        name = input.nextLine(); //get name

        while(true) {

            System.out.println("Enter TSS:");
            TSS = input.nextLine(); //get TSS

            if (test.isDouble(TSS)) {
                break; //break loop if type is double
            } else {
                System.out.println("Invalid input.");
            }
        }

        while (true) {

            System.out.println("Enter COD:");
            COD = input.nextLine(); //get COD

            if(test.isDouble(COD)){
                break; //break loop if type is double
            }
            else{
                System.out.println("Invalid input.");
            }
        }

        while (true) {

            System.out.println("Enter BOD:");
            BOD = input.nextLine(); //get BOD

            if(test.isDouble(BOD)){
                break; //break loop if type is double
            }
            else{
                System.out.println("Invalid input.");
            }
        }

        while (true) {

            System.out.println("Enter area:");
            area = input.nextLine(); //get area

            if(test.isDouble(area)){
                break; //break loop if type is double
            }
            else{
                System.out.println("Invalid input.");
            }
        }

        while (true) {
            System.out.println("Enter energy:");
            energy = input.nextLine(); //get energy

            if(test.isDouble(energy)){
                break; //break loop if type is double
            }
            else{
                System.out.println("Invalid input.");
            }
        }

        for(Tech count : holdTech){ //count number of original codes in linked list
            if (Integer.parseInt(type)== count.getType()){
                code++; //get new code number
            }
        }

        Tech newTech = new Tech(Integer.parseInt(type),code, name, Double.parseDouble(TSS), Double.parseDouble(COD), Double.parseDouble(BOD), Double.parseDouble(area), Double.parseDouble(energy));
        holdTech.add(newTech); //add new entry into linked list

        return holdTech; //return new linked list
    }
}
